spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cars?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Op009oP!
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
